# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: unless-stopped  
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - backend      
    ports:
      - '27017:27017'
  application:
    container_name: nutridata_app    
    build: .
    ports:
      - '4000:4000'
    networks:
      - backend
networks:
  dockernet:
    driver: host  
  backend:
    driver: bridge