version: 2.1
jobs:
  build:
    docker: 
      - image: fedora # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: ls
  deploy:    
    machine:
      enabled: true
    steps:    
      - add_ssh_keys:
          fingerprints:            
            - "5a:59:6e:f5:c0:a1:82:da:1e:61:2e:48:de:d3:4a:91"
      - run:
          name: Capturando chaves de acesso
          command: ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
      - checkout # check out the code in the project directory     
      - run:
          name: Copiando arquivos
          command: |            
            rsync -avh --delete --rsh="ssh -o StrictHostKeyChecking=no "  . $SSH_USER@$SSH_HOST:/root/NutriData
      # - run: 
      #     name: Pull na applicação
      #     command: |
      #       ssh $SSH_USER@$SSH_HOST "cd /root/Nutridata && git pull"
      - run: 
          name: Parando coitainers Docker-Compose
          command: |
            ssh $SSH_USER@$SSH_HOST "cd /root/NutriData && docker-compose stop application && docker-compose kill application"
      - run: 
          name: Iniciando coitainers Docker-Compose
          command: |
            ssh $SSH_USER@$SSH_HOST "cd /root/NutriData docker-compose up -d --no-deps --build application"
      


workflows:
  version: 2
  build-and-deploy:
    jobs:      
      - deploy:         
          filters:
            branches:
              only: master