"""empty message

Revision ID: 70101c97d7aa
Revises: 65ed6274de38
Create Date: 2018-12-12 17:42:30.256338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70101c97d7aa'
down_revision = '65ed6274de38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fontesdedados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fontesdedados')
    # ### end Alembic commands ###
